server:
  port: ${PORT:8090}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    hostname: localhost

spring:
  application:
    name: user-api-hr
  jpa:
    open-in-view: true
    #Postgresql JPA
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    #PostGreSQL Datasource
    url: jdbc:postgresql://localhost:5434/hrSystem
    username: postgres
    password: changeme



