server:
  port: ${PORT:8100}

spring:
  application:
    name: payroll-api-hr

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    hostname: localhost
