server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
  renewalPercentThreshold: 0.85
  wait-time-in-ms-when-sync-empty: 0
  enableSelfPreservation: false
